/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:db3aef1f-6f47-4eb4-8fd2-1f7daab927f5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4DeStWfF1",
    "aws_user_pools_web_client_id": "2cjnno3ofslgtkf3ttttcpep8m",
    "oauth": {}
};


export default awsmobile;
